<?php
/**
 * Created by PhpStorm.
 * User: yang
 * Date: 2018/8/15
 * Time: 23:53
 */

namespace app\home\controller;


use think\Controller;
use think\Session;
use think\Request;
use app\home\controller\Car;
use app\index\model\Article;
use app\index\model\Brand;
use app\index\model\Cate;
use app\index\model\Comment;
use app\index\model\Member;

class Base extends Controller
{
//    protected function _initialize()
//    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
//            define("MEMBER_ID",Session::get("member_id"));
//
//    }
    protected function islogin(){
        $id=Session::get("member_id");
        if(empty($id)){
            $this->error("用户未登录",url("/home/member/login"));
        }
    }
    protected function seclogin(){
        $id=Session::get("member_id");
        if(!empty($id)){
            $this->error("用户已登录",url("/home/index/index"));
        }
    }

    //删除功能

    public function getc(){
        $controllers=request()->controller();
        return $controllers;
    }
    public function getm(){
        $controllers=request()->controller();
        $models='\\app\\index\\model\\'.$controllers;
        return $models;
    }

    public function alldelete(){
        $models=$this->getm();
        $ids=input("post.delete_id/a");
        foreach ($ids as $id){
            $models::update(["is_delete"=>1],["id"=>$id]);
            $models::destroy($id);
        }
        return ['status'=>1,'message'=>"删除成功"];
    }
    public function unDelete(){
        $models=$this->getm();
        $models::update(["delete_time"=>null,"is_delete"=>0],["is_delete"=>1]);
    }
//    编辑模板渲染
    public function edit(Request $request){
        $id=$request->param("id");
        $controllers=$this->getc();
        $models=$this->getm();
        $result=$models::get($id);
        $data=$result->getData();
        $this->view->assign("data",$data);
        return $this->view->fetch($controllers."_edit");
    }
    public function editcheck(Request $request){
        $data=$this->request->param();
        $id=$this->request->param("id");
        $models=$this->getm();
        $status = 0;
        $messages = '更新失败';
        $model=new $models();
        $res=$model->validates($data);
        $messages=$res["messages"];

        if($res["result"]==true){
            $insterTrue=$models::update($data,["id"=>$id]);
            if($insterTrue!=null){
                $status=1;
                $messages="更新成功";
            }

        }
        return ['status'=>$status,'message'=>$messages];
    }
    public function comdata(){
        $branddata=Brand::all();
        $catedata=Cate::all();
        $articles=new Article();
        $article=$articles->order("create_time","desc")->select();
        $carmodel=new Car();
        $car=$carmodel->getcar();

        return [
            "catedata"=>$catedata,
            "branddata"=>$branddata,
            "car"=>$car,
            "article"=>$article,
        ];
    }


}